apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chess-backend-ingress
  namespace: chess-backend-stateless
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "36000"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "36000"
spec:
  tls:
  - hosts:
    - ec2-65-0-75-103.ap-south-1.compute.amazonaws.com
    secretName: chess-tls-secret
  rules:
  - host: "ec2-65-0-75-103.ap-south-1.compute.amazonaws.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: chess-backend-service
            port:
              number: 80
