apiVersion: apps/v1
kind: Deployment

metadata:
  name: chess-backend-deploy
  namespace: chess-backend-stateless
  labels:
    component: backend-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend-pod
      
  template:
    metadata:
      labels:
        component: backend-pod
    spec:
      containers:
      - name: chess-backend-container
        image: vishalbhatsoori/chess-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: KAFKA_BROKER
          value: "kafka-0.kafka-headless.data.svc.cluster.local:9092"
        
